### PR TITLE
Bump hcsshim to v0.8.5

### PR DESCRIPTION
**Pull request by arjun024**
* Update vendored hcsshim to greenhouse-org/hcsshim, branch: upstream-v0.8.5-mod
(https://github.com/greenhouse-org/hcsshim/tree/upstream-v0.8.5-mod).

* This branch of the hcsshim fork contains all commits from Microsoft/hcsshim v.0.8.5 rebased
on top of all commits previously made by the garden windows team to add extra endpoint info (see https://github.com/Microsoft/hcsshim/compare/master...greenhouse-org:extra-endpoint-info).

* The fork-branch also includes the fix to the race condition in syscallWatcher (See PR Microsoft/hcsshim#431).

* Tested on: Windows 1803.2, Windows 1709.17

Tracker-story: https://www.pivotaltracker.com/story/show/162997839

cc: @achasveachas

### CODE REVIEW

**Comment by arjun024** [comment]
@sesmith177 @natalieparellano -- Thought we'll run it by you and see if you have any comments before merging.

**Comment by sesmith177** [comment]
I have two small concerns here:
1. For our fork of hcsshim, it's probably easiest just to create a new commit on top of the v0.8.5 branch instead of a rebase. That way, anyone looking at that branch will be able to tell easily what the diff is
2. Adding fsnotify to Gopkg.toml seems odd to me -- it's not a dependency of winc or hcsshim that I can tell

**Comment by achasveachas** [comment]
1. Guess we can do that. But someone can tell just by comparing the branches -> https://github.com/Microsoft/hcsshim/compare/v0.8.5...greenhouse-org:upstream-v0.8.5-mod
2. That seems to be a [known bug](https://github.com/golang/dep/issues/1799). We ran into it in [groot-windows](https://github.com/cloudfoundry/groot-windows/blob/0aceca260b134a61c0de9e1e78c68b70ad57aecf/Gopkg.toml#L61) as well. This seems to be the only way around it.

**Comment by arjun024** [comment]
On the fork, we have made one commit that takes all the changes in "our" previous commits and pushed it on top of v0.8.5. Now the git history is clean -- our changes are on top of the Microsoft changes. See https://github.com/greenhouse-org/hcsshim/commit/d3cfe7c848cd05f76295a6a5c7be83c8b0683a06

**Pull request merged**
